version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: diprec-postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "dbpassword123"
      POSTGRES_DB: "diprec_db"
    ports:
      - "5432:5432"
    volumes:
      - diprec-postgres-data:/var/lib/postgresql/data
    networks:
      - diprec-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thesis -d thesis"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  diprec-postgres-data:
networks:
  diprec-net:
